languageCode = "en-us"
title = "Tea, Coffee & Code"
baseurl = "https://trietphm.github.io/"
publishDir= "."
enableEmoji= true
googleAnalytics= "UA-93009521-1"
theme= "ghostwriter"

BaseUrl = "https://trietphm.github.io/"

[Author]
	name = "Triet Pham"
	profile = "http://github.com/trietphm"

[params]

# your name to display by the copyright sign
# default: undefined
AuthorName = "Triet Pham"

# tagline to show beneath homepage h1
# default: undefined
Tagline = "Hello, world!"

# number of posts to show on index
# default: 10
#HomepagePosts = 3

# if set to true, social links will be displayed in the footer
# default: undefined
SocialLinks = true

disqusShortname = "trietpham"

# default: undefined
GithubUsername = "trietphm"

# default: undefined
TwitterUsername = "trietphm"

github = "https://github.com/trietphm"
shareTwitter = true
shareFacebook = true
shareGooglePlus = true

[blackfriday]
extensions = ["hardLineBreak"]

[[menu.main]]
	name = "Blog"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Reading list"
	url = "/page/reading-list/"
	weight = 2

[[menu.main]]
	name = "Friends"
	url = "/page/friends/"
	weight = 3

[[menu.main]]
	name = "About"
	url = "/page/about/"
	weight = 4
